version: '3.4'

services:
  fscback:
    image: fscback.azurecr.io/fscback:v1
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4898:4898
