version: '3.4'

services:
  front:
    image: library.app.front
    build:
      context: front
      dockerfile: /Dockerfile
    environment:
      - NODE_ENV=porduction
    ports:
      - :3000
  
  back:
    image: library.app.back
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=porduction
    ports:
      - :4898